# .github/workflows/app.yaml
name: Project Tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.1
      
      - name: Install pipenv
        run: |
             python -m pip install --upgrade pipenv wheel
  
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Install package
        run: |
          pip install . 

      - name: Unit tests with pytest
        run: |
          python -m pytest -vv tests/*py